// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAg4RTwOArDArMSZv3KR52j8TOKaMYP6l4',
    appId: '1:791882803752:web:47b478e4747f6e60a1631d',
    messagingSenderId: '791882803752',
    projectId: 'flutter-chat-app-f339d',
    authDomain: 'flutter-chat-app-f339d.firebaseapp.com',
    storageBucket: 'flutter-chat-app-f339d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqnon1LOu8jgkDhZPVNqUR8G0nkwrxaVY',
    appId: '1:791882803752:android:16ec3248e2cffb84a1631d',
    messagingSenderId: '791882803752',
    projectId: 'flutter-chat-app-f339d',
    storageBucket: 'flutter-chat-app-f339d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCYIZ55KHPDXOf7dCIJExBE2sZbkBDUlE',
    appId: '1:791882803752:ios:87d54f00b318c4a1a1631d',
    messagingSenderId: '791882803752',
    projectId: 'flutter-chat-app-f339d',
    storageBucket: 'flutter-chat-app-f339d.firebasestorage.app',
    iosBundleId: 'com.example.firebaseChatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBCYIZ55KHPDXOf7dCIJExBE2sZbkBDUlE',
    appId: '1:791882803752:ios:87d54f00b318c4a1a1631d',
    messagingSenderId: '791882803752',
    projectId: 'flutter-chat-app-f339d',
    storageBucket: 'flutter-chat-app-f339d.firebasestorage.app',
    iosBundleId: 'com.example.firebaseChatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAg4RTwOArDArMSZv3KR52j8TOKaMYP6l4',
    appId: '1:791882803752:web:76ee6553138bfc48a1631d',
    messagingSenderId: '791882803752',
    projectId: 'flutter-chat-app-f339d',
    authDomain: 'flutter-chat-app-f339d.firebaseapp.com',
    storageBucket: 'flutter-chat-app-f339d.firebasestorage.app',
  );
}
